# Generate a .env with random secrets if one doesn't exist yet.
# Idempotent, running again does nothing if .env exists.

$ErrorActionPreference = "Stop"
$envFile = ".env"
$MinPasswordChars = 8
$MaxPasswordBytes = 72

function New-RandomToken {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '').Replace('/', '').Substring(0, 32)
}

# Resolve the first-run admin password: TF_ADMIN_PASSWORD in the environment
# if set, otherwise ask for it. The scheduler creates the admin account from
# this on first boot and refuses to start without one (R-040), so a blank or
# rejected value must stop this script before .env is written, not after.
function Get-AdminPassword {
    if ($env:TF_ADMIN_PASSWORD) {
        return $env:TF_ADMIN_PASSWORD
    }
    $secure = Read-Host -Prompt "Choose an admin password ($MinPasswordChars-$MaxPasswordBytes bytes)" -AsSecureString
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    } finally {
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

if (Test-Path $envFile) {
    Write-Host ".env already exists. Leaving it alone."
    Write-Host "(delete it and re-run if you want fresh secrets)"
    exit 0
}

$adminPassword = Get-AdminPassword
$adminPasswordBytes = [System.Text.Encoding]::UTF8.GetByteCount($adminPassword)
if ($adminPassword.Length -lt $MinPasswordChars -or $adminPasswordBytes -gt $MaxPasswordBytes) {
    Write-Error "TF_ADMIN_PASSWORD must be $MinPasswordChars-$MaxPasswordBytes bytes (bcrypt's limit). Nothing was written."
    exit 1
}

$pgPass = New-RandomToken
$authSecret = New-RandomToken
$timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")

@"
# Generated by bootstrap.ps1 on $timestamp.
# Do not commit this file.

# Postgres password, used by the postgres container and the scheduler.
TF_PG_PASSWORD=$pgPass

# Cookie-signing secret. Stable across restarts so existing logins survive.
TF_AUTH_SECRET=$authSecret

# First-run admin password. The scheduler creates the admin account from
# this on first boot; there is no web page that can create one. Log in as
# 'admin' with this value.
TF_ADMIN_PASSWORD=$adminPassword

# Where to find your media. Edit these to point at your library.
TF_LIBRARY_MOVIES=./media/movies
TF_LIBRARY_TV=./media/tv

# Web port (default 8000) and DB/Redis ports.
# TF_PORT=8000
# TF_DB_PORT=5432
# TF_REDIS_PORT=6379
"@ | Set-Content -Path $envFile -Encoding utf8

New-Item -ItemType Directory -Force -Path "./media/movies" | Out-Null
New-Item -ItemType Directory -Force -Path "./media/tv" | Out-Null

Write-Host "Wrote $envFile with random secrets and created ./media/{movies,tv}."
Write-Host "Your admin login is 'admin' plus the TF_ADMIN_PASSWORD line in $envFile."
Write-Host "Edit TF_LIBRARY_MOVIES / TF_LIBRARY_TV in .env to point at your real library."
Write-Host "Then: docker compose up -d"
