#!/usr/bin/env bash
# Generate a .env with random secrets if one doesn't exist yet.
# Idempotent — running again does nothing if .env already has the
# required keys.

set -euo pipefail

ENV_FILE=".env"

random_token() {
    # 32 bytes URL-safe base64. Falls back to /dev/urandom + tr if openssl is missing.
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32 | tr -d '=+/' | cut -c1-44
    else
        head -c 64 /dev/urandom | base64 | tr -d '=+/\n' | cut -c1-44
    fi
}

if [[ -f "$ENV_FILE" ]]; then
    echo ".env already exists — leaving it alone."
    echo "(delete it and re-run if you want fresh secrets)"
    exit 0
fi

PG_PASS="$(random_token)"
AUTH_SECRET="$(random_token)"

cat > "$ENV_FILE" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Do not commit this file.

# Postgres password — used by the postgres container and the scheduler.
TF_PG_PASSWORD=${PG_PASS}

# Cookie-signing secret. Stable across restarts so existing logins survive.
TF_AUTH_SECRET=${AUTH_SECRET}

# Where to find your media. Edit these to point at your library.
# These paths must exist on the host before 'docker compose up'.
TF_LIBRARY_MOVIES=./media/movies
TF_LIBRARY_TV=./media/tv

# Web port (default 8000) and DB/Redis ports.
# TF_PORT=8000
# TF_DB_PORT=5432
# TF_REDIS_PORT=6379
EOF

mkdir -p ./media/movies ./media/tv

echo "Wrote $ENV_FILE with random secrets and created ./media/{movies,tv}."
echo "Edit TF_LIBRARY_MOVIES / TF_LIBRARY_TV in .env to point at your real library."
echo "Then: docker compose up -d"
