# Generate a .env with random secrets if one doesn't exist yet.
# Idempotent — running again does nothing if .env exists.

$ErrorActionPreference = "Stop"
$envFile = ".env"

function New-RandomToken {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '').Replace('/', '').Substring(0, 32)
}

if (Test-Path $envFile) {
    Write-Host ".env already exists — leaving it alone."
    Write-Host "(delete it and re-run if you want fresh secrets)"
    exit 0
}

$pgPass = New-RandomToken
$authSecret = New-RandomToken
$timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")

@"
# Generated by bootstrap.ps1 on $timestamp.
# Do not commit this file.

# Postgres password — used by the postgres container and the scheduler.
TF_PG_PASSWORD=$pgPass

# Cookie-signing secret. Stable across restarts so existing logins survive.
TF_AUTH_SECRET=$authSecret

# Where to find your media. Edit these to point at your library.
TF_LIBRARY_MOVIES=./media/movies
TF_LIBRARY_TV=./media/tv

# Web port (default 8000) and DB/Redis ports.
# TF_PORT=8000
# TF_DB_PORT=5432
# TF_REDIS_PORT=6379
"@ | Set-Content -Path $envFile -Encoding utf8

New-Item -ItemType Directory -Force -Path "./media/movies" | Out-Null
New-Item -ItemType Directory -Force -Path "./media/tv" | Out-Null

Write-Host "Wrote $envFile with random secrets and created ./media/{movies,tv}."
Write-Host "Edit TF_LIBRARY_MOVIES / TF_LIBRARY_TV in .env to point at your real library."
Write-Host "Then: docker compose up -d"
