"""The admin is born on the machine, never over the network.

R-040: a fresh instance used to be claimable by whoever loaded /setup
first, and on the Linode deploy Caddy publishes the hostname to the public
certificate transparency logs seconds before the operator has set a
password. There is no longer an HTTP door to create the admin: startup
makes it from the machine's own configuration, so the instance is owned
before it can serve a request.

The password is never generated by the app either. Handing one back
through a log is a weaker permission than the account deserves (on
Kubernetes `kubectl logs` needs far less than the exec that recovery
needs) and shipped logs outlive the instance, so TF_ADMIN_PASSWORD is
required and boot fails loudly without it.
"""

import pytest

from transcode_forge.admin import ensure_admin
from transcode_forge.db import DBConnection
from transcode_forge.repos import users as user_repo

GOOD_PW = "operator-chosen-password"


class TestEnsureAdmin:
    async def test_creates_the_admin_from_the_configured_password(self, db: DBConnection):
        created = await ensure_admin(db, GOOD_PW)

        assert created is True
        assert await user_repo.authenticate(db, GOOD_PW) is True

    async def test_second_boot_is_a_no_op(self, db: DBConnection):
        await ensure_admin(db, GOOD_PW)

        assert await ensure_admin(db, "a-completely-different-password") is False
        # A restart must not rotate the credential out from under the
        # operator, even if the environment changed underneath it.
        assert await user_repo.authenticate(db, GOOD_PW) is True

    async def test_refuses_to_boot_unowned_when_nothing_is_configured(self, db: DBConnection):
        with pytest.raises(RuntimeError, match="TF_ADMIN_PASSWORD"):
            await ensure_admin(db, None)

        assert await user_repo.has_admin(db) is False

    async def test_race_loser_defers_to_the_replica_that_won(self, db: DBConnection, monkeypatch):
        """Two scheduler replicas can boot against one database. users.username
        is UNIQUE, so the loser's INSERT raises; it must report 'already owned'
        rather than crash the process."""
        await ensure_admin(db, GOOD_PW)

        calls = {"n": 0}
        real_has_admin = user_repo.has_admin

        async def has_admin_racing(conn: DBConnection) -> bool:
            calls["n"] += 1
            if calls["n"] == 1:
                return False  # the winner had not committed yet when we looked
            return await real_has_admin(conn)

        monkeypatch.setattr(user_repo, "has_admin", has_admin_racing)

        assert await ensure_admin(db, "the-losers-password") is False
        assert await user_repo.authenticate(db, GOOD_PW) is True


class TestPasswordLengthBound:
    """bcrypt refuses over 72 BYTES and raises rather than truncating, so a
    password that passes a character-count check can still blow up inside
    the hash. At startup that is a crash loop, not a validation error, so
    the bound is on encoded bytes and it is checked before any DB work."""

    async def test_rejects_a_password_too_short_to_be_worth_anything(self, db: DBConnection):
        with pytest.raises(ValueError, match="TF_ADMIN_PASSWORD"):
            await ensure_admin(db, "short")

        assert await user_repo.has_admin(db) is False

    async def test_rejects_a_password_bcrypt_could_not_hash(self, db: DBConnection):
        with pytest.raises(ValueError, match="TF_ADMIN_PASSWORD"):
            await ensure_admin(db, "a" * 73)

        assert await user_repo.has_admin(db) is False

    async def test_counts_bytes_not_characters(self, db: DBConnection):
        # 40 accented characters is 80 bytes — short-looking, still unusable.
        with pytest.raises(ValueError, match="bytes"):
            await ensure_admin(db, "é" * 40)

        assert await user_repo.has_admin(db) is False

    async def test_accepts_the_longest_password_bcrypt_takes(self, db: DBConnection):
        assert await ensure_admin(db, "a" * 72) is True
        assert await user_repo.authenticate(db, "a" * 72) is True


class TestFailedStartupReleasesResources:
    """A lifespan that raises after init_db used to leave the database
    connection open. uvicorn reports "Application startup failed. Exiting."
    and then the process never exits, because the connection's worker thread
    outlives it — so a container sits there serving nothing instead of
    failing visibly. Refusing to boot is only useful if it actually stops."""

    async def test_a_refused_boot_closes_the_database(self, tmp_path, monkeypatch):
        import transcode_forge.main as main_mod
        from transcode_forge.config import Settings

        closed: list[object] = []

        async def spy_close_db(db: object) -> None:
            closed.append(db)

        monkeypatch.setattr(main_mod, "close_db", spy_close_db)

        settings = Settings(
            db_url=f"sqlite:///{(tmp_path / 'refused.db').as_posix()}",
            demo_mode=True,
            admin_password="",
        )
        app = main_mod.create_app(settings=settings)

        with pytest.raises(RuntimeError, match="TF_ADMIN_PASSWORD"):
            async with main_mod.lifespan(app):
                pass

        assert closed, "the database was left open on a failed startup"
